### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by CieNTi** [corteXnzt/hrs3300_test#1]
Hello there @corteXnzt !

I reached your GitHub after searching during a lot of time for an already opened B57 smart watch picture with no luck, just to ask you if at some point you have some picture of it, when you opened it for dev (as read on the forum, you already closed it ... but just in case I have the luck to you to have it hehehe).

The reason behind this request, it is because now they are building exact replicas but with HS6620D inside ... keeping every single line of all descriptions as it still has the NRF inside, so could be good for me to have your pictures for my dispute, without actually opening a unit I have (so scratch a little the plastics, gum it again after ... you know).

| Expected inside the B57 | Found inside my replica B57 |
| :----- | :----- |
| NRF52832 | HS6620D |
| 32 Mb flash | 16 Mb flash (25VQ128AWEG) |
| HRS3300 | WK1070 |
| 180 mAh | 170 mAh |

Do you know which accelerometer is expected to be inside a Nordic B57?

For you to see this replicas, I let you here some pics of it.

Fake HS6620D-based B57 link: https://www.aliexpress.com/item/4000384065182.html

Since my dispute they added the "WearFit 2.0" at the beginning, but they still has all others NRF references (like the "HeroBandIII" compatibility, which as "Da Fit", is for NRF devices only).

![See how they offer a NRF, but you can see how the version screen differs](https://user-images.githubusercontent.com/5205702/87898938-ea477480-ca4f-11ea-9842-27f87fde7fd3.jpeg)

> See how they offer a NRF, but you can see how the version screen differs

![Zoom to see the HS6620D there](https://user-images.githubusercontent.com/5205702/87898944-ee739200-ca4f-11ea-8f2e-9d3ea7eef280.jpeg)

> Zoom to see the HS6620D there

![Zoom to read the flash chip reference](https://user-images.githubusercontent.com/5205702/87898949-f03d5580-ca4f-11ea-83e8-375463fc9bfd.jpeg)

> Zoom to read the flash chip reference

Thanks in advance!

**Comment by XlashDev** [comment]
Hi! 

This all I have on my laptop. I'll check at home later on my desktop pc if there are still copies of the pictures taken closely.
The accelerometer used is a BMA421.

![DSC_0423](https://user-images.githubusercontent.com/49268713/87900975-63fb5480-ca88-11ea-8ddc-b6aca4999fea.JPG)

![DSC_0427](https://user-images.githubusercontent.com/49268713/87900920-40d0a500-ca88-11ea-8dba-4941dde5c8a5.JPG)

![DSC_0425](https://user-images.githubusercontent.com/49268713/87900862-1aab0500-ca88-11ea-8f6a-2bd703b53870.JPG)

**Comment by CieNTi** [comment]
Amazing! Thank you very much!

**Comment by XlashDev** [comment]
You're welcome! Btw I just noticed this now, you can zoom in and you can view the 52832 word on the chip .

**Comment by CieNTi** [comment]
Perfect :D
